class indigo_iam (
  $iam_version                    = $indigo_iam::params::iam_version,
  $iam_repo_branch                = $indigo_iam::params::iam_repo_branch,
  $service_manage                 = $indigo_iam::params::service_manage,
  $service_ensure                 = $indigo_iam::params::service_ensure,
  $service_enable                 = $indigo_iam::params::service_enable,
  $active_profiles                = $indigo_iam::params::active_profiles,
  $java_opts                      = $indigo_iam::params::java_opts,
  $iam_base_url                   = $indigo_iam::params::iam_base_url,
  $iam_issuer                     = $indigo_iam::params::iam_issuer,
  $iam_use_forwarded_headers      = $indigo_iam::params::iam_use_forwarded_headers,
  $iam_key_store_location         = $indigo_iam::params::iam_key_store_location,
  $generate_keystore              = $indigo_iam::params::generate_keystore,
  $iam_organisation_name          = $indigo_iam::params::iam_organisation_name,
  $iam_db_host                    = $indigo_iam::params::iam_db_host,
  $iam_db_port                    = $indigo_iam::params::iam_db_port,
  $iam_db_schema                  = $indigo_iam::params::iam_db_schema,
  $iam_db_username                = $indigo_iam::params::iam_db_username,
  $iam_db_password                = $indigo_iam::params::iam_db_password,
  $iam_notification_disable       = $indigo_iam::params::iam_notification_disable,
  $iam_notification_from          = $indigo_iam::params::iam_notification_from,
  $iam_notification_task_delay    = $indigo_iam::params::iam_notification_task_delay,
  $iam_notification_admin_address = $indigo_iam::params::iam_notification_admin_address,
  $iam_mail_host                  = $indigo_iam::params::iam_mail_host,
  $iam_google_client_id           = $indigo_iam::params::iam_google_client_id,
  $iam_google_client_secret       = $indigo_iam::params::iam_google_client_secret,
  $iam_google_redirect_uris       = $indigo_iam::params::iam_google_redirect_uris,
  $iam_saml_entity_id             = $indigo_iam::params::iam_saml_entity_id,
  $iam_saml_keystore              = $indigo_iam::params::iam_saml_keystore,
  $iam_saml_keystore_password     = $indigo_iam::params::iam_saml_keystore_password,
  $iam_saml_key_id                = $indigo_iam::params::iam_saml_key_id,
  $iam_saml_key_password          = $indigo_iam::params::iam_saml_key_password,
  $iam_saml_idp_metadata          = $indigo_iam::params::iam_saml_idp_metadata,) inherits indigo_iam::params {
  #

  class { 'indigo_iam::install':
    iam_version     => $iam_version,
    iam_repo_branch => $iam_repo_branch,
  } ~>
  class { 'indigo_iam::configure':
    active_profiles                => $active_profiles,
    java_opts                      => $java_opts,
    iam_base_url                   => $iam_base_url,
    iam_issuer                     => $iam_issuer,
    iam_use_forwarded_headers      => $iam_use_forwarded_headers,
    iam_key_store_location         => $iam_key_store_location,
    generate_keystore              => $generate_keystore,
    iam_organisation_name          => $iam_organisation_name,
    iam_db_host                    => $iam_db_host,
    iam_db_port                    => $iam_db_port,
    iam_db_schema                  => $iam_db_schema,
    iam_db_username                => $iam_db_username,
    iam_db_password                => $iam_db_password,
    iam_notification_disable       => $iam_notification_disable,
    iam_notification_from          => $iam_notification_from,
    iam_notification_task_delay    => $iam_notification_task_delay,
    iam_notification_admin_address => $iam_notification_admin_address,
    iam_mail_host                  => $iam_mail_host,
    iam_google_client_id           => $iam_google_client_id,
    iam_google_client_secret       => $iam_google_client_secret,
    iam_google_redirect_uris       => $iam_google_redirect_uris,
    iam_saml_entity_id             => $iam_saml_entity_id,
    iam_saml_keystore              => $iam_saml_keystore,
    iam_saml_keystore_password     => $iam_saml_keystore_password,
    iam_saml_key_id                => $iam_saml_key_id,
    iam_saml_key_password          => $iam_saml_key_password,
    iam_saml_idp_metadata          => $iam_saml_idp_metadata,
  } ~>
  class { 'indigo_iam::service':
    service_manage => $service_manage,
    service_ensure => $service_ensure,
    service_enable => $service_enable,
  }
}
